version: "3.8"
services:
  nepse_scraper:
    build: .
    container_name: nepse_scraper
    volumes:
      - .:/app
  user: "${UID:-1000}:${GID:-1000}"
    command: ["python", "sharesansar_tsp_scraper.py"]
