name: Daily Sharesansar Scrape

on:
  schedule:
    # 6:00 PM Asia/Kathmandu (UTC+5:45) is 12:15 PM UTC
    - cron: "15 12 * * 0-4" # Sunday (0) to Thursday (4)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily sharesansar scraper
        run: python sharesansar_api_daily_scraper.py

      - name: Commit and push updated data if any
        run: |
          git config --global user.name "0Ankit0"
          git config --global user.email "ankitpaudel.1373@gmail.com"
          DATE=$(date +"%Y-%m-%d")
          git add sharesansarAPI/*.csv || true
          if git diff --cached --quiet; then
            echo "No new data to commit."
          else
            git commit -m "updated the data for date : $DATE"
            git push
          fi
